//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintablesApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtAddress {
            get {
                return ((string)(this["txtAddress"]));
            }
            set {
                this["txtAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtFrom {
            get {
                return ((string)(this["txtFrom"]));
            }
            set {
                this["txtFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtPhone {
            get {
                return ((string)(this["txtPhone"]));
            }
            set {
                this["txtPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("                       VFS LOGISTICS SUPPORT A.E.\n           Ταχυμεταφορές αντικε" +
            "ιμένων & εγγράφων\n       ΚΕΝΤΡΙΚΟ: ΓΑΡΔΕΝΙΑΣ 30-ΑΧΑΡΝΕΣ Τ.Κ 136 72\n           ΑΦ" +
            "Μ  998300724   -   ΔΟΥ:  ΦΑΕ ΑΘΗΝΩΝ\n   ΥΠΜΑ: Κωνσταντίνου Υδραίου 71 - ΡΟΔΟΣ Τ.Κ" +
            ". 85100")]
        public string txtStamp {
            get {
                return ((string)(this["txtStamp"]));
            }
            set {
                this["txtStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("                       VFS LOGISTICS SUPPORT A.E.\n           Ταχυμεταφορές αντικε" +
            "ιμένων & εγγράφων\n       ΚΕΝΤΡΙΚΟ: ΓΑΡΔΕΝΙΑΣ 30-ΑΧΑΡΝΕΣ Τ.Κ 136 72\n           ΑΦ" +
            "Μ  998300724   -   ΔΟΥ:  ΦΑΕ ΑΘΗΝΩΝ\n   ΥΠΜΑ: Κωνσταντίνου Υδραίου 71 - ΡΟΔΟΣ Τ.Κ" +
            ". 85100")]
        public string StampDefaultValue {
            get {
                return ((string)(this["StampDefaultValue"]));
            }
            set {
                this["StampDefaultValue"] = value;
            }
        }
    }
}
